version: "3.8"

volumes:
  etc_wireguard:

services:
  wg-easy:
    build: .
    container_name: wg-easy

    environment:
      # Language
      - LANG=de

      # Required Hostname
      - WG_HOST=52.220.142.94

      # Custom Ports to Forward (read in entrypoint.sh)
      - PORTS=5050,5051,5052,5053,5054,5055,6666,7777,8888,9090,25565

      # Optional WireGuard Settings
      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
      # - WG_PORT=51820
      # - PORT=51821
      # - WG_CONFIG_PORT=92820
      - WG_DEFAULT_ADDRESS=10.8.0.2
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24,10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0

    volumes:
      - etc_wireguard:/etc/wireguard

    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
      - "5050:5050/tcp"
      - "5051:5051/tcp"

    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW  # Uncomment if you're using Podman

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
